# Generated by Django 5.2 on 2025-04-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
    ]
