# Generated by Django 5.2 on 2025-05-03 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0002_event_end_time_event_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_planner.event'),
        ),
    ]
