# Generated by Django 5.2 on 2025-05-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0003_remove_attendance_name_attendance_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_planner.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
