# Generated by Django 5.2 on 2025-05-04 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0004_attendancing_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancing',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_planner.event'),
        ),
    ]
