# Generated by Django 5.2 on 2025-05-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0005_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='user',
        ),
    ]
